%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/melodic/.*$
%global __requires_exclude_from ^/opt/ros/melodic/.*$

Name:           ros-melodic-octomap-mapping
Version:        0.6.4
Release:        1%{?dist}
Summary:        ROS octomap_mapping package

License:        BSD
URL:            http://ros.org/wiki/octomap_mapping
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-melodic-octomap-server
BuildRequires:  ros-melodic-catkin

%description
Mapping tools to be used with the OctoMap library, implementing a 3D occupancy
grid mapping.

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/melodic

%changelog
* Wed Jan 08 2020 Wolfgang Merkt <w.merkt+oss@gmail.com> - 0.6.4-1
- Autogenerated by Bloom

* Mon Jan 28 2019 Wolfgang Merkt <w.merkt+oss@gmail.com> - 0.6.3-0
- Autogenerated by Bloom

* Sun Jan 27 2019 Wolfgang Merkt <w.merkt+oss@gmail.com> - 0.6.2-0
- Autogenerated by Bloom

* Fri Jan 18 2019 Armin Hornung <armin@hornung.io> - 0.6.1-0
- Autogenerated by Bloom

